---
application:
  name: "starrybot"
  project: "StarryBot"
  organization: "QoveryCommunity"
databases:
- type: mysql # database type
  version: 8.0 # database version
  name: starry # database name (must be unique)
routers:
- name: "main-starrybot"
  routes:
  - application_name: "starrybot"
    paths:
    - "/*"
