---
application:
  name: "starrybot"
  project: "StarryBot"
  organization: "QoveryCommunity"
databases:
- type: mysql # database type
  version: "8.0.19" # database version
  name: Starry # database name (must be unique)
routers:
- name: "main-starrybot"
  routes:
  - application_name: "starrybot"
    paths:
    - "/*"
